-- 虚拟男友项目 — PostgreSQL 初始库表
-- 执行示例：psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/postgresql/001_init.sql

-- =============================================================================
-- 1. 用户表 users
-- =============================================================================
CREATE TABLE users (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     varchar(32)  NOT NULL,
  password_hash varchar(255) NOT NULL,
  email        varchar(255) NOT NULL,
  nickname     varchar(32)  NOT NULL,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz,
  status       smallint     NOT NULL DEFAULT 1,
  CONSTRAINT ck_users_status CHECK (status IN (0, 1))
);

-- 用户名、邮箱唯一（不区分大小写）
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

CREATE INDEX idx_users_created_at ON users (created_at);

COMMENT ON TABLE users IS '注册用户：登录名、密码哈希、邮箱、昵称与账号状态';
COMMENT ON COLUMN users.id IS '用户主键序号，自增';
COMMENT ON COLUMN users.username IS '登录用户名；唯一性由 lower(username) 唯一索引保证';
COMMENT ON COLUMN users.password_hash IS '密码哈希（如 bcrypt），禁止存明文';
COMMENT ON COLUMN users.email IS '注册邮箱；唯一性由 lower(email) 唯一索引保证';
COMMENT ON COLUMN users.nickname IS '展示昵称';
COMMENT ON COLUMN users.created_at IS '注册时间';
COMMENT ON COLUMN users.updated_at IS '资料或安全相关字段最后更新时间';
COMMENT ON COLUMN users.status IS '账号状态：1 正常，0 禁用';

-- =============================================================================
-- 2. 角色字典表 characters（与业务 character id 对齐，便于外键）
-- =============================================================================
CREATE TABLE characters (
  id          smallserial PRIMARY KEY,
  code        varchar(32)  NOT NULL,
  name        varchar(32)  NOT NULL,
  sort_order  smallint     NOT NULL DEFAULT 0,
  is_active   boolean      NOT NULL DEFAULT true,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_characters_code UNIQUE (code)
);

COMMENT ON TABLE characters IS '可对话角色字典，供会话表外键引用';
COMMENT ON COLUMN characters.id IS '角色主键序号，自增';
COMMENT ON COLUMN characters.code IS '角色代码，如 shenyu、lushiyan，与程序内 CharacterId 一致';
COMMENT ON COLUMN characters.name IS '角色展示名称';
COMMENT ON COLUMN characters.sort_order IS '首页或列表排序权重，越小越靠前';
COMMENT ON COLUMN characters.is_active IS '是否对用户可见';
COMMENT ON COLUMN characters.created_at IS '记录创建时间';

-- 与当前项目四位角色一致（id 按插入顺序为 1–4）
INSERT INTO characters (code, name, sort_order, is_active) VALUES
  ('shenyu',    '沈屿',   1, true),
  ('lushiyan',  '陆时衍', 2, true),
  ('jiangyubai','江屿白', 3, true),
  ('huoyanchen','霍砚琛', 4, true)
ON CONFLICT (code) DO NOTHING;

-- =============================================================================
-- 3. 聊天会话表 chat_sessions（每用户 × 每角色一条主会话）
-- =============================================================================
CREATE TABLE chat_sessions (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  character_id     smallint     NOT NULL REFERENCES characters (id) ON DELETE RESTRICT,
  title            varchar(64),
  last_message_at  timestamptz,
  created_at       timestamptz  NOT NULL DEFAULT now(),
  updated_at       timestamptz,
  CONSTRAINT uq_chat_sessions_user_character UNIQUE (user_id, character_id)
);

CREATE INDEX idx_chat_sessions_user ON chat_sessions (user_id);
CREATE INDEX idx_chat_sessions_last_msg ON chat_sessions (user_id, last_message_at DESC NULLS LAST);

COMMENT ON TABLE chat_sessions IS '用户与某一角色的会话容器；每人每角色默认一条';
COMMENT ON COLUMN chat_sessions.id IS '会话主键序号，自增';
COMMENT ON COLUMN chat_sessions.user_id IS '所属用户';
COMMENT ON COLUMN chat_sessions.character_id IS '对话角色，关联 characters.id';
COMMENT ON COLUMN chat_sessions.title IS '会话标题，可空';
COMMENT ON COLUMN chat_sessions.last_message_at IS '最后一条消息时间，用于列表排序';
COMMENT ON COLUMN chat_sessions.created_at IS '会话创建时间';
COMMENT ON COLUMN chat_sessions.updated_at IS '会话最后更新时间';

-- =============================================================================
-- 4. 聊天消息表 chat_messages
-- =============================================================================
CREATE TABLE chat_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  bigint       NOT NULL REFERENCES chat_sessions (id) ON DELETE CASCADE,
  role        varchar(16)  NOT NULL,
  content     text         NOT NULL,
  reply_type  varchar(32),
  extra_json  jsonb,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT ck_chat_messages_role CHECK (role IN ('user', 'assistant'))
);

CREATE INDEX idx_chat_messages_session_time ON chat_messages (session_id, created_at);

COMMENT ON TABLE chat_messages IS '会话内的单条消息（用户或助手）';
COMMENT ON COLUMN chat_messages.id IS '消息主键序号，自增';
COMMENT ON COLUMN chat_messages.session_id IS '所属会话';
COMMENT ON COLUMN chat_messages.role IS '发送方：user 用户，assistant 助手';
COMMENT ON COLUMN chat_messages.content IS '消息正文（文本）';
COMMENT ON COLUMN chat_messages.reply_type IS '多模态类型：text / voice / image 等，与接口约定一致';
COMMENT ON COLUMN chat_messages.extra_json IS '扩展字段：语音 URL、图片、image_ref 等 JSON';
COMMENT ON COLUMN chat_messages.created_at IS '消息产生时间';
