-- 生图结果持久化记录表（R2 永久链接归档）
-- 执行示例：psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/postgresql/003_generated_images.sql

CREATE TABLE IF NOT EXISTS generated_images (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint REFERENCES users (id) ON DELETE SET NULL,
  character_id smallint NOT NULL REFERENCES characters (id) ON DELETE RESTRICT,
  image_ref    varchar(64) NOT NULL,
  prompt       text NOT NULL,
  source_url   text NOT NULL,
  r2_key       text NOT NULL,
  image_url    text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_generated_images_user_created_at
  ON generated_images (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_generated_images_character_created_at
  ON generated_images (character_id, created_at DESC);

COMMENT ON TABLE generated_images IS 'AI 生图持久化记录：保存上游临时地址与 R2 永久地址';
COMMENT ON COLUMN generated_images.id IS '记录主键序号，自增';
COMMENT ON COLUMN generated_images.user_id IS '触发生图的用户（可空，未登录时为空）';
COMMENT ON COLUMN generated_images.character_id IS '关联角色，引用 characters.id';
COMMENT ON COLUMN generated_images.image_ref IS '业务侧图片引用标识，用于定位回复模板';
COMMENT ON COLUMN generated_images.prompt IS '最终发送给生图模型的提示词';
COMMENT ON COLUMN generated_images.source_url IS '上游生图服务返回的临时 URL';
COMMENT ON COLUMN generated_images.r2_key IS '对象在 R2 中的 Key';
COMMENT ON COLUMN generated_images.image_url IS '可公开访问的 R2 永久 URL';
COMMENT ON COLUMN generated_images.created_at IS '记录创建时间';
